
package igu;

import java.awt.event.KeyEvent;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;

public class Pantalla extends javax.swing.JFrame {
private DefaultTableModel modeloDatos;
 
    public Pantalla() {
        initComponents();
        
        // Inicializacion de elementos de la tabla
        modeloDatos = new DefaultTableModel(); // Inicializar modeloDatos
        Carrito.setModel(modeloDatos); // Establecer el modelo en la tabla
        modeloDatos.addColumn("Asiento");
        modeloDatos.addColumn("Edad");
        modeloDatos.addColumn("Tipo entrada");
        modeloDatos.addColumn("Precio ($)");
        modeloDatos.addColumn("Descuento (%)");
        modeloDatos.addColumn("Precio final ($)");        
       Carrito.getColumnModel().getColumn(0).setPreferredWidth(50);
       Carrito.getColumnModel().getColumn(1).setPreferredWidth(50);
       Carrito.getColumnModel().getColumn(2).setPreferredWidth(100);
       Carrito.getColumnModel().getColumn(3).setPreferredWidth(60);
       Carrito.getColumnModel().getColumn(4).setPreferredWidth(95);
        Carrito.getColumnModel().getColumn(5).setPreferredWidth(85);
    }

    public JComboBox<String> getTipoAsiento() {
        return tipoAsiento;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tipoAsiento = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tEdad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Carrito = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Venta de entradas Teatro Moro");

        jLabel2.setText("Seleccione tipo de asiento");

        tipoAsiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A1", "A2", "B1", "B2", "C1", "C2", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M" }));
        tipoAsiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoAsientoActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/igu/teatro.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel3.setText("Ingrese edad");

        tEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tEdadKeyTyped(evt);
            }
        });

        Carrito.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(Carrito);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Total a cancelar:");

        Total.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Total.setToolTipText("");

        jButton1.setText("Agregar al carro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Nueva venta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tipoAsiento, 0, 90, Short.MAX_VALUE)
                                            .addComponent(tEdad)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(18, 18, 18)
                                            .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(6, 6, 6))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tipoAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Total))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addComponent(jLabel4))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipoAsientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoAsientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoAsientoActionPerformed

    private void tEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tEdadKeyTyped
         char car = evt.getKeyChar();
          String textoActual = tEdad.getText();

            // Verifica si el carácter es un dígito y si el texto actual tiene menos de dos dígitos
            if (!Character.isDigit(car) || textoActual.length() >= 2) {
                evt.consume(); // No permite ingresar más caracteres
            }
    }//GEN-LAST:event_tEdadKeyTyped


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// Obtener los valores de los campos
    String asiento = tipoAsiento.getSelectedItem().toString();
    int edad = Integer.parseInt(tEdad.getText()); // Convertir el texto a entero
    String tipoEntrada; // Variable para almacenar el tipo de entrada
    int precio; // Variable para almacenar el precio
    int[] retorno = new int[3];
    // Determinar el tipo de entrada basado en la edad
    if (edad < 18) {
        tipoEntrada = "Estudiante";
    } else if (edad > 64) {
        tipoEntrada = "Tercera Edad";
    } else {
        tipoEntrada = "Público General";
    }
    
    // Calcular el precio
    retorno = calcularPrecio(edad);
    
    // Agregar los valores a la tabla
    Object[] fila = {asiento, edad, tipoEntrada, retorno[0], retorno[1], retorno[2]};
    modeloDatos.addRow(fila);
    
    // Actualizar el total a cancelar
    actualizarTotal();
    tEdad.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        modeloDatos.setRowCount(0);  
        Total.setText("");
        tEdad.setText("");
        tipoAsiento.setSelectedItem("A1");
    }//GEN-LAST:event_jButton2ActionPerformed
    
    // Ejemplo de una función para calcular el precio según la edad
private int[] calcularPrecio(int edad) {
    int precioBase;
    int precioFinal;
    int[] retorno = new int[3];
    String tipoAsientoSeleccionado = tipoAsiento.getSelectedItem().toString();
    
    // Asignar el precio base según el tipo de asiento
    switch (tipoAsientoSeleccionado) {
        case "A1":
        case "B1":
        case "C1":
            precioBase = 40000;
            break;
        case "A2":
        case "B2":
        case "C2":
        case "D":
        case "E":
        case "F":
            precioBase = 30000;
            break;
        case "G":
        case "M":
            precioBase = 60000;
            break;
        case "H":
        case "I":
        case "J":
        case "K":
        case "L":
            precioBase = 15000;
            break;
        default:
            precioBase = 0; // Precio base por defecto
            break;
    }
       retorno[0]=precioBase;
       retorno[1]=0;
       retorno[2]=precioBase;
    // Aplicar ajustes según la edad
    if (edad < 18) {
        retorno[2] -= 0.1*precioBase; // Descuento para menores de 18 años
        retorno[1]=10;
    } else if (edad >= 65) {
        retorno[2] -= 0.15*precioBase; // Descuento para mayores de 65 años
        retorno[1]=15;
    }
    
    return retorno;
}


private void actualizarTotal() {
    // Suma
    int total = 0;
    for (int i = 0; i < modeloDatos.getRowCount(); i++) {
        total += (int) modeloDatos.getValueAt(i, 5); // Sumar el precio de cada fila
    }
    Total.setText("$" + Integer.toString(total)); // Actualizar el label del total a cancelar
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Carrito;
    private javax.swing.JLabel Total;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tEdad;
    private javax.swing.JComboBox<String> tipoAsiento;
    // End of variables declaration//GEN-END:variables
}
